- src/moderations/page.tsx
- src/ui/table/index.ts
</p>
---
Closes https://github.com/betagouv/hyyypertool/issues/11
> feat(moderations): make the whole moderation line clickable

- src/moderations/:id/03.tsx
</p>
---
Refs: f75e8648190ef6bc553267bf87beb6ea19ae15d4.
Closes https://github.com/betagouv/hyyypertool/issues/14
> revert(legacy): add confirm prompt on mark as processed buttons

- src/moderations/page.tsx
- src/moderations/repository.ts
- src/moderations/route.tsx
> feat(moderations): add hide join organization filter the table

- src/moderations/page.tsx
- src/moderations/route.tsx
> refacto(moderations): rename hide_non_verified_domain

- src/auth/route.ts
- src/common/session.ts
- src/legacy/services/zammad_api.ts
- src/moderations/:id/route.tsx
> feat(moderation): try to guest the owner of the ticket

- src/legacy/organizations/Table.tsx
- src/legacy/routes/users/:id/organizations/index.tsx
- src/legacy/users/ModerationTable.tsx
- src/legacy/users/Table.tsx
- src/organizations/:id/members/route.tsx
</p>
---
Closes https://github.com/betagouv/hyyypertool/issues/32
> fix: link icon is just to tiny

- src/moderations/:id/03.tsx
- src/moderations/:id/reponse_templates.tsx
> feat(moderation): add livreurs / mobilic response

- src/organizations/:id/members/route.tsx
> fix(organization): use common pagination schema

- src/moderations/:id/reponse_templates.tsx
</p>
---
Closes [#43](https://github.com/betagouv/hyyypertool/issues/43)
> feat(moderation): add refus prestataires response

- e2e/cypress/support/step_definitions/general.ts
- e2e/features/moderations/jean_join_abracadabra.feature
- e2e/features/moderations/jean_join_dinum.feature
- e2e/features/organizations/dinum.feature
- e2e/package.json
- package.json
- src/database/moncomptepro/seed/insert.ts
- src/legacy/routes/users/:id/index.tsx
- src/moderations/:id/02.tsx
- src/organizations/:id/Fiche.tsx
> test(e2e): add moderations testing

- .github/workflows/e2e.yml
- e2e/.gitignore
- e2e/README.md
- e2e/cypress.config.ts
- e2e/cypress/support/step_definitions/general.ts
- e2e/features/moderations/jean_bon_join_abracadabra.feature
- e2e/features/moderations/jean_bon_join_dinum.feature
- e2e/features/moderations/pierre_bon_join_aldp.feature
- e2e/features/users/raphael.feature
- e2e/package.json
- e2e/pnpm-lock.yaml
- src/bootstrap.ts
- src/database/moncomptepro/seed/delete.ts
- src/database/moncomptepro/seed/insert.ts
> test(e2e): add asso ALDP testing

- src/legacy/services/zammad_api.ts
- src/moderations/:id/03.tsx
- src/moderations/:id/email/Message.tsx
- src/moderations/:id/email/route.tsx
> feat(moderation): create ticket from moderation reponse 

- src/legacy/routes/leaders/index.tsx
- src/moderations/:id/02.tsx
- src/moderations/:id/email/ListZammadArticles.tsx
- src/organizations/:id/Fiche.tsx
</p>
---
Closes [#44](https://github.com/betagouv/hyyypertool/issues/44)
> bug(moderation): open external link in new tabs

- e2e/features/moderations/richard_bon_join_dengi.feature
- src/api_ref.ts
- src/database/moncomptepro/seed/insert.ts
- src/moderations/:id/02.tsx
- src/moderations/:id/Duplicate_Warning.tsx
- src/moderations/duplicate_warning/route.tsx
- src/moderations/repository.ts
- src/moderations/route.tsx
</p>
---
Closes https://github.com/betagouv/hyyypertool/issues/65
> fix(moderation): duplicate_warning not found

- src/moderations/:id/About_User.tsx
> feat(moderation): add search organization and email domaine

- src/moderations/:id/Header.tsx
- src/moderations/moderation_type_to_emoji.tsx
- src/moderations/page.tsx
> feat(moderation): add moderation type emoji in header

- e2e/features/moderations/marie_bon_join_bosch.feature
- src/database/moncomptepro/seed/insert.ts
> test(e2e): add non_verified_domain moderation

- src/moderations/page.tsx
> feat(moderation): inline filter form

- src/moderations/page.tsx
- src/moderations/repository.ts
- src/moderations/route.tsx
> feat(moderations): show the processed moderation on search

- .github/workflows/e2e.yml
> ci(github): parallel e2e tests

- .github/workflows/e2e.yml
> ci(github): parallel e2e tests (2)

- package.json
- packages/~/users/repository/src/get_user_by_id.ts
- src/moderations/:id/Duplicate_Warning.tsx
- tsconfig.json
> refacto(users): move repository internal code

- packages/~/app/layout/src/root.ts
- packages/~/app/urls/src/hx_urls.ts
- packages/~/moderations/api/src/context.ts
- packages/~/moderations/api/src/index.tsx
- packages/~/moderations/api/src/page.tsx
> feat(moderation): force check show processed requests on search

- e2e/cypress/support/step_definitions/general.ts
- e2e/features/moderations/jean_bon_join_abracadabra.feature
- packages/~/infra/moncomptepro/database/src/seed/delete.ts
- packages/~/infra/moncomptepro/database/src/seed/insert.ts
- packages/~/moderations/api/src/:id/03.tsx
> feat(moderation): auto go back after marked as proceseed

- packages/~/infra/moncomptepro/database/src/seed/delete.ts
</p>
---
Inspired by https://github.com/betagouv/moncomptepro/commit/26ccd8c02c1f6bb3460f4ec4694afe293440e0ea#diff-18fd1c6f5d8a5c5ccfb35fd22aaab26c22ae542a5632ee7d1b522846400bf98e
> chore(database): restart some table index while seeding

- packages/~/app/urls/src/legacy.ts
- packages/~/app/urls/src/pattern.d.ts
- packages/~/moderations/api/src/:id/02.tsx
- packages/~/users/api/src/:id/index.ts
- packages/~/users/api/src/:id/organizations/index.tsx
- src/legacy/routes/users/:id/index.tsx
> refacto(users): move organization api internal code

- packages/~/moderations/api/src/:id/03.tsx
> fix(moderation): scroll to latest message

- packages/~/moderations/api/src/:id/reponse_templates.tsx
> fix(moderation): typo missing e to plateforme

- packages/~/moderations/api/src/index.tsx
> fix(moderation): parsed search query can't be nullish

- packages/~/infra/moncomptepro/database/src/seed/insert.ts
- packages/~/moderations/api/package.json
- packages/~/moderations/api/src/context.test.ts
- packages/~/moderations/api/src/context.ts
- packages/~/moderations/repository/src/get_moderations_list.ts
> chore(deps): update dependencies

- e2e/cypress/support/step_definitions/general.ts
- e2e/features/moderations/jean_bon_join_abracadabra.feature
- packages/~/app/ui/package.json
- packages/~/app/ui/src/menu/index.ts
- packages/~/organizations/api/src/:id/domains/external/Table.tsx
> feat(ui): share menu item style

- packages/~/moderations/api/src/:id/User_In_Organization_Table.tsx
- packages/~/moderations/api/src/:id/page.tsx
- packages/~/organizations/repository/src/get_organisations_by_user_id.ts
- packages/~/users/api/src/:id/organizations/Table.tsx
> fix(moderation): organization member stays empty

- packages/~/moderations/api/src/:id/User_In_Organization_Table.tsx
> feat(moderation): trigger reload user in organization

- packages/~/app/ui/src/hx_table/Foot.tsx
- packages/~/moderations/api/src/page.tsx
- packages/~/organizations/repository/src/get_organisations_by_user_id.ts
> fix(moderation): ensure to use the current page on refresh

- packages/~/moderations/api/src/page.tsx
> fix(moderation): include the day in page request

- packages/~/app/ui/src/hx_table/Foot.tsx
> feat(ui): add refresh button

- .github/workflows/e2e.yml
> ci(github): cypress install

- packages/~/app/core/src/html/index.ts
- packages/~/app/ui/package.json
- packages/~/app/ui/src/callout/index.ts
- packages/~/app/ui/src/form/index.ts
- packages/~/moderations/api/src/:id/Actions.tsx
- packages/~/moderations/api/src/:id/Desicison.tsx
- packages/~/moderations/api/src/:id/Desicison_Context.tsx
- packages/~/moderations/api/src/:id/Header.tsx
- packages/~/moderations/api/src/:id/Member_Invalid.tsx
- packages/~/moderations/api/src/:id/Member_Valid.tsx
- packages/~/moderations/api/src/:id/MessageInfo.tsx
- packages/~/moderations/api/src/:id/page.tsx
- packages/~/moderations/api/src/:id/responses/already_signed.tsx
- packages/~/moderations/api/src/:id/responses/context.ts
- packages/~/moderations/api/src/:id/responses/first_last_name.tsx
- packages/~/users/repository/src/get_emails_by_organization_id.ts
- tailwind.config.ts
> feat(moderation): desicison section first iteration

- packages/~/app/ui/package.json
- packages/~/app/ui/src/button/scripts/copy_to_clipboard.test.ts
- packages/~/app/ui/src/button/scripts/copy_to_clipboard.ts
- packages/~/app/ui/src/button/scripts/index.ts
- packages/~/moderations/api/src/:id/Member_Invalid.tsx
> feat(ui): add copy_to_clipboard script

- packages/~/app/core/src/config/env.ts
- packages/~/organizations/repository/src/get_organisations_by_user_id.ts
- packages/~/users/api/src/:id/organizations/Table.tsx
- packages/~/users/api/src/:id/organizations/context.tsx
> fix(users): false empty organization

- packages/~/app/urls/src/pattern.d.ts
- packages/~/moderations/api/src/:id/$procedures/rejected.ts
- packages/~/moderations/api/src/:id/Member_Invalid.tsx
- packages/~/moderations/api/src/:id/Member_Valid.tsx
> feat(moderation): rejected behavior

- packages/~/app/ui/src/time/LocalTime.tsx
- packages/~/moderations/api/src/:id/$procedures/comment_message.ts
- packages/~/moderations/api/src/:id/$procedures/rejected.ts
- packages/~/moderations/api/src/:id/$procedures/reprocess.ts
- packages/~/moderations/api/src/:id/$procedures/validate.ts
- packages/~/moderations/api/src/:id/Header.tsx
- packages/~/moderations/api/tsconfig.json
> feat(moderation): use comment field as history

- e2e/features/moderations/jean_bon_join_abracadabra.feature
- e2e/features/moderations/marie_bon_join_bosch.feature
- packages/~/moderations/api/src/:id/$procedures/validate.ts
- packages/~/moderations/api/src/:id/Desicison_Context.tsx
- packages/~/moderations/api/src/:id/Member_Valid.tsx
- packages/~/moderations/lib/src/Moderation_Type.ts
> feat(moderation): send notification with a checkbox

- packages/~/moderations/api/src/:id/$procedures/processed.ts
- packages/~/moderations/api/src/:id/duplicate_warning/Duplicate_Warning.tsx
- packages/~/moderations/api/src/:id/duplicate_warning/index.tsx
- packages/~/moderations/repository/src/get_duplicate_moderations.ts
> fix(moderation): allow to refuse without notifying the user

- packages/~/moderations/api/src/:id/duplicate_warning/Duplicate_Warning.tsx
> fix(moderation): go back after mark as processed

- packages/~/moderations/api/src/page.tsx
> fix(moderations): force autoreload on load

- packages/~/moderations/api/src/page.tsx
Reverts betagouv/hyyypertool#165
> Revert "fix(moderations): force autoreload on load"

- packages/~/infra/moncomptepro/database/src/seed/insert.ts
- packages/~/moderations/api/src/:id/duplicate_warning/Duplicate_Warning.tsx
> feat(moderation): detect same user name

- packages/~/organizations/api/src/leaders/index.tsx
> fix(organization): ensure to remove unknow depot date form the document list

- .github/workflows/sentry.yml
> ci(github): add sentry release workflow

- packages/~/moderations/api/src/:id/Member_Invalid.tsx
- packages/~/moderations/api/src/:id/responses/chorus_pro.tsx
> feat(moderation): add reponse for Chorus Pro

- packages/~/app/api/src/index.ts
> feat(app): use hono/compress

- .github/workflows/e2e.yml
- docker-compose.yaml
- mocks/docker-compose.mocks.yaml
> chore(mock): use docker compose include

- .github/workflows/e2e.yml
- packages/~/infra/moncomptepro/database/README.md
- packages/~/infra/moncomptepro/database/src/drizzle/0000_fat_jetstream.sql
> ci(github): remove extra postgres service

- packages/~/infra/zammad/api/package.json
- packages/~/infra/zammad/api/src/index.test.ts
- packages/~/infra/zammad/api/src/index.ts
- packages/~/infra/zammad/api/tsconfig.json
> fix(zammad): no more immutable errors

- packages/~/moderations/api/src/:id/About_Organisation.tsx
- packages/~/moderations/api/src/:id/context.ts
> feat(moderation): replace id by adresse

- packages/~/moderations/api/src/:id/About_Organisation.tsx
> feat(moderations): add see leader list link

- packages/~/moderations/api/src/:id/About_Organisation.tsx
> fix(moderations): leader list link use siren

- packages/hono-slotify/src/__snapshots__/indext.test.tsx.snap
- packages/hono-slotify/src/indext.test.tsx
- packages/~/infra/moncomptepro/database/src/index.ts
- packages/~/infra/moncomptepro/database/src/seed/delete.ts
- packages/~/infra/moncomptepro/database/src/seed/insert.ts
- packages/~/infra/moncomptepro/database/src/seed/unicorn.ts
- packages/~/infra/moncomptepro/database/src/testing/index.ts
- packages/~/moderations/api/src/:id/responses/__snapshots__/already_signed.test.tsx.snap
- packages/~/moderations/api/src/:id/responses/already_signed.test.tsx
- packages/~/moderations/api/src/:id/responses/already_signed.tsx
- packages/~/users/repository/src/get_emails_by_organization_id.test.ts
- packages/~/users/repository/src/get_emails_by_organization_id.ts
> feat(moderation): only list email of user with the same family name

- packages/~/organizations/api/src/domaines/index.tsx
- packages/~/organizations/repository/src/get_unverified_organizations.ts
> feat(organizations): preview unverified domaines in the table

- packages/~/app/sentry/src/index.ts
> fix(sentry): use global scope on HEAD and OPTIONS requests

- packages/~/organizations/api/src/:id/Edit_Domain.tsx
- packages/~/organizations/api/src/:id/Fiche.tsx
- packages/~/organizations/api/src/:id/context.ts
- packages/~/organizations/api/src/:id/index.tsx
- packages/~/organizations/api/src/:id/page.tsx
- packages/~/organizations/api/src/domaines/context.ts
- packages/~/organizations/api/src/domaines/index.tsx
- packages/~/organizations/repository/src/get_organization_by_id.ts
- packages/~/organizations/repository/src/get_unverified_organizations.ts
> refacto(organizations): use page request context

- packages/~/infra/moncomptepro/lib/src/verification_type.ts
- packages/~/organizations/api/src/:id/members/Table.tsx
<div align="center">
</div>
Closes #21
Closes #378
> feat(organisations): add no_validation_means_available

- packages/~/app/ui/src/button/components/search.tsx
- packages/~/organizations/api/src/:id/domains/internal/Table.tsx
Closes #377<div align="center">
</div>
> feat(organisations): add google search per domain

- packages/~/users/api/src/:id/context.ts
- packages/~/users/api/src/:id/index.tsx
- packages/~/users/api/src/:id/page.tsx
- packages/~/users/repository/src/get_user_by_id.ts
> refacto(user): use page request context

- packages/~/users/repository/src/get_user_by_id.ts
<div align="center">
</div>
Closes #168
> perf(user): exact column user query

- packages/~/moderations/api/src/:id/About_Organisation.tsx
- packages/~/moderations/api/src/:id/About_User.tsx
- packages/~/moderations/api/src/:id/page.tsx
> style(moderations): align investigation sections

- packages/~/moderations/api/src/:id/About_User.tsx
<div align="center">
</div>
---
Closes #330
Closes #84
> feat(moderations): add profile detail section

- packages/~/moderations/api/src/:id/About_Organisation.tsx
- packages/~/moderations/api/src/:id/About_User.tsx
- packages/~/moderations/api/src/:id/Actions.tsx
- packages/~/moderations/api/src/:id/Domain_Organization.tsx
- packages/~/moderations/api/src/:id/Header.tsx
- packages/~/moderations/api/src/:id/Member_Invalid.tsx
- packages/~/moderations/api/src/:id/Member_Valid.tsx
- packages/~/moderations/api/src/:id/Members_Of_Organization_Table.tsx
- packages/~/moderations/api/src/:id/MessageInfo.tsx
- packages/~/moderations/api/src/:id/Moderation_Exchanges.tsx
- packages/~/moderations/api/src/:id/Organizations_Of_User_Table.tsx
- packages/~/moderations/api/src/:id/context.ts
- packages/~/moderations/api/src/:id/index.tsx
- packages/~/moderations/api/src/:id/page.tsx
- packages/~/moderations/api/src/:id/responses/accountant.tsx
- packages/~/moderations/api/src/:id/responses/already_signed.test.tsx
- packages/~/moderations/api/src/:id/responses/already_signed.tsx
- packages/~/moderations/api/src/:id/responses/chorus_pro_error.tsx
- packages/~/moderations/api/src/:id/responses/contractors.tsx
- packages/~/moderations/api/src/:id/responses/first_last_name.tsx
- packages/~/moderations/api/src/:id/responses/link_with_eduction_gouv_fr.tsx
- packages/~/moderations/api/src/:id/responses/link_with_organization.tsx
- packages/~/moderations/api/src/:id/responses/mobilic.tsx
- packages/~/moderations/api/src/:id/responses/use_official_email.tsx
- packages/~/moderations/api/src/:id/responses/use_pro_email.tsx
> refacto(moderation): use page request context

- packages/~/app/urls/src/pattern.d.ts
- packages/~/moderations/api/src/:id/Members_Of_Organization_Table.tsx
- packages/~/organizations/api/src/:id/members/Table.tsx
- packages/~/organizations/api/src/:id/members/context.ts
- packages/~/organizations/api/src/:id/members/index.tsx
- packages/~/organizations/api/src/:id/page.tsx
> fix(organization): keep page after row action

- packages/~/organizations/repository/src/add_authorized_domain.ts
- packages/~/organizations/repository/src/add_verified_domain.ts
> fix(organization): update the updated_at

- packages/~/users/api/src/:id/page.tsx
<div align="center">
</div>
Closes #332
> feat(users): add confirm before deleting a user account

- e2e/features/moderations/marie_bon_join_bosch.feature
- packages/~/app/ui/src/plurial/index.test.ts
- packages/~/app/ui/src/plurial/index.ts
> fix(ui): use fr-FR rules

- packages/~/app/api/src/index.ts
- packages/~/app/middleware/src/authorized.test.ts
- packages/~/app/middleware/src/authorized.ts
- packages/~/moderations/api/src/index.tsx
- packages/~/organizations/api/src/index.tsx
- packages/~/users/api/src/index.e2e.test.ts
- packages/~/users/api/src/index.tsx
> refactor(api): get allow user list from context config

- packages/~/organizations/repository/src/get_unverified_domains.test.ts
- packages/~/organizations/repository/src/get_unverified_domains.ts
> fix(domains): search not working due to query typo

- packages/~/organizations/repository/src/get_unverified_domains.test.ts
- packages/~/organizations/repository/src/get_unverified_domains.ts
> test: ensure to not list trackdechets_postal_mail

- packages/~/organizations/api/src/domaines/index.tsx
- packages/~/organizations/repository/src/get_unverified_domains.ts
> fix(domain): line order and crazy refresh

- packages/~/organizations/api/src/:id/domains/Table.tsx
> feat(domains): add verification link on the row

- packages/~/organizations/repository/src/get_unverified_domains.test.ts
- packages/~/organizations/repository/src/get_unverified_domains.ts
> feat(domains): exclude unipersonnelle organizations

- packages/~/moderations/api/src/:id/responses/invalid_job.tsx
> :art: (responses) fix indentation

- packages/~/app/layout/src/__snapshots__/main.test.tsx.snap
- packages/~/app/layout/src/__snapshots__/root.test.tsx.snap
- packages/~/app/layout/src/root.ts
<p align="center"><img src="https://media3.giphy.com/media/l2JhL1AzTxORUTDlC/200.webp?cid=790b7611vx51sm3y4cizvvm1957e2x5y3fyetjfias4j9x2r&ep=v1_gifs_search&rid=200.webp&ct=g"></p>
> fix(icon): display icons from dsfr 🤓

- e2e/features/organizations/dinum.feature
- packages/~/moderations/api/src/:id/Members_Of_Organization_Table.tsx
- packages/~/organizations/api/src/:id/context.ts
- packages/~/organizations/api/src/:id/index.tsx
- packages/~/organizations/api/src/:id/page.tsx
> feat(organisation): fold organization members by default

- packages/~/infra/moncomptepro/database/src/seed/zombie.ts
- packages/~/organizations/repository/src/get_unverified_domains.test.ts
- packages/~/organizations/repository/src/get_unverified_domains.ts
> feat(domains): remove free domains from the list

- docker-compose.yaml
Linked https://github.com/numerique-gouv/moncomptepro/pull/758
> chore(docker): update to postgres 15.8

- packages/~/moderations/ui/src/Actions/responses/__snapshots__/non_teaching_agent.test.tsx.snap
- packages/~/moderations/ui/src/Actions/responses/non_teaching_agent.test.tsx
- packages/~/moderations/ui/src/Actions/responses/non_teaching_agent.tsx
> test(moderation): update snapshot

- packages/~/users/api/src/:id/index.tsx
- packages/~/users/lib/src/usecase/ResetPassword.test.ts
- packages/~/users/lib/src/usecase/ResetPassword.ts
- packages/~/users/lib/src/usecase/index.ts
- packages/~/users/ui/src/templates/index.ts
> fix(users): notify the user of the password reset

- packages/~/organizations/api/src/:id/domains/Table.tsx
> fix(organization): eol after domain creation date

- bun.lock
- packages/~/infra/crisp/lib/package.json
> refactor(crisp): move to @gouvfr-lasuite/proconnect.crisp

- packages/~/moderations/ui/src/Actions/responses/__snapshots__/agent_comcom_comaglo.test.tsx.snap
- packages/~/moderations/ui/src/Actions/responses/agent_comcom_comaglo.test.tsx
- packages/~/moderations/ui/src/Actions/responses/agent_comcom_comaglo.tsx
> fix(moderation): fix wrong label and describe test on moderation

- packages/~/app/core/src/config/env.ts
- packages/~/moderations/api/src/:id/$procedures/rejected.ts
- packages/~/moderations/lib/src/context/rejected.ts
- packages/~/moderations/lib/src/usecase/respond_to_ticket.ts
- packages/~/users/api/src/:id/index.tsx
- packages/~/users/lib/src/usecase/ResetMFA.test.ts
- packages/~/users/lib/src/usecase/ResetMFA.ts
- packages/~/users/lib/src/usecase/ResetPassword.test.ts
- packages/~/users/lib/src/usecase/ResetPassword.ts
> fix(crips): add CRISP_RESOLVE_DELAY

- packages/~/infra/moncomptepro/lib/src/sdk.ts
> refactor(moncomptepro): use sdk file export point

- packages/~/moderations/ui/src/Actions/ResponseMessageSelector.tsx
- packages/~/moderations/ui/src/Actions/context.ts
<p align="center"><img src="https://media.giphy.com/media/1TSHxNUZh1FdzUpFWK/giphy.gif?cid=790b7611nu1ersbvfdoe75p2sz4h54izmydshncp71a9litu&ep=v1_gifs_search&rid=giphy.gif&ct=g"></p>
> feature(searchBar): add searchbar for response type

- packages/~/app/urls/src/pattern.d.ts
- packages/~/moderations/ui/src/OrganizationsByUser/OrganizationsByUser.tsx
- packages/~/moderations/ui/src/UsersByOrganization/UsersByOrganization.tsx
- packages/~/users/api/src/:id/organizations/Table.tsx
- packages/~/users/api/src/:id/organizations/context.tsx
- packages/~/users/api/src/:id/organizations/index.tsx
- packages/~/users/api/src/:id/page.tsx
> fix(organization): list by user id pagination

- packages/~/moderations/ui/src/Actions/responses/__snapshots__/first_and_last_name_inversion.test.tsx.snap
- packages/~/moderations/ui/src/Actions/responses/__snapshots__/missing_name.test.tsx.snap
- packages/~/moderations/ui/src/Actions/responses/__snapshots__/occupation_incorrectly_entered.test.tsx.snap
- packages/~/moderations/ui/src/Actions/responses/first_and_last_name_inversion.tsx
- packages/~/moderations/ui/src/Actions/responses/missing_name.tsx
- packages/~/moderations/ui/src/Actions/responses/occupation_incorrectly_entered.tsx
<p align="center"><img src="https://media.giphy.com/media/6OGZJiQKGEh3uuTbdb/giphy.gif?cid=790b76118eb5fv2s30m9pi5b8zw8nw7i3ble9xxo96d13mq9&ep=v1_gifs_search&rid=giphy.gif&ct=g"></p>
> update(moderation): replace old mcp link with pc link

- packages/~/moderations/ui/src/Actions/responses/user_with_existing_pc_account.test.tsx
- packages/~/moderations/ui/src/Actions/responses/user_with_existing_pc_account.tsx
<p align="center"><img src="https://media.giphy.com/media/goKgmdgnBfbYhsZFy9/giphy.gif?cid=82a1493balmut3jwyrpu6o8lmdjxta2kb9bt4t1yh0y5rsv2&ep=v1_gifs_trending&rid=giphy.gif&ct=g"></p>
> update(moderation): update content of mail from user_with_existing_pc_account

- packages/~/moderations/ui/src/Actions/responses/__snapshots__/first_and_last_name_inversion.test.tsx.snap
- packages/~/moderations/ui/src/Actions/responses/__snapshots__/missing_name.test.tsx.snap
- packages/~/moderations/ui/src/Actions/responses/__snapshots__/name_incorrectly_entered.test.tsx.snap
- packages/~/moderations/ui/src/Actions/responses/__snapshots__/occupation_incorrectly_entered.test.tsx.snap
- packages/~/moderations/ui/src/Actions/responses/__snapshots__/occupation_incorrectly_entered_not_blocking.test.tsx.snap
- packages/~/moderations/ui/src/Actions/responses/first_and_last_name_inversion.tsx
- packages/~/moderations/ui/src/Actions/responses/missing_name.tsx
- packages/~/moderations/ui/src/Actions/responses/name_incorrectly_entered.test.tsx
- packages/~/moderations/ui/src/Actions/responses/name_incorrectly_entered.tsx
- packages/~/moderations/ui/src/Actions/responses/occupation_incorrectly_entered.tsx
- packages/~/moderations/ui/src/Actions/responses/occupation_incorrectly_entered_not_blocking.test.tsx
- packages/~/moderations/ui/src/Actions/responses/occupation_incorrectly_entered_not_blocking.tsx
<p align="center"><img src="https://media.giphy.com/media/tXVELlqovG6jJHHixz/giphy.gif?cid=ecf05e47z1bnh024cix7er9ntbtt8bjvh1jp1sm8uwcjyphl&ep=v1_gifs_search&rid=giphy.gif&ct=g"></p>
> feat(moderation): update responses types

- e2e/bun.lock
- e2e/package.json
<div align=center>
</div>
---
\following https://github.com/cypress-io/github-action/issues/1408
> chore(deps): update to cypress@14.2.1

- packages/~/moderations/api/src/:id/$procedures/processed.ts
- packages/~/moderations/api/src/:id/$procedures/rejected.ts
- packages/~/moderations/api/src/:id/$procedures/validate.ts
- packages/~/moderations/lib/src/comment_message.ts
- packages/~/moderations/lib/src/context/rejected.ts
- packages/~/moderations/lib/src/usecase/mark_moderatio_as_rejected.ts
- packages/~/moderations/lib/src/usecase/mark_moderation_as.ts
> feat(moderations): add why its rejected

- packages/~/app/layout/src/__snapshots__/main.test.tsx.snap
- packages/~/app/layout/src/__snapshots__/root.test.tsx.snap
- packages/~/app/layout/src/root.ts
- packages/~/app/sentry/src/index.ts
Linked to https://github.com/numerique-gouv/hyyypertool/pull/833
> chore(sentry): use sentry_trace_meta_tags

- packages/~/moderations/ui/src/Actions/RefusalModal.tsx
<p align="center"><img src="https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExam5rN2l1OXNpY201b3UzYWR2OWkxNmEwemhnOXZ2YjM5Z21mdTIxbiZlcD12MV9naWZzX3NlYXJjaCZjdD1n/MuHJcSI9ySLsrNo59Q/giphy.gif"></p>
> fix(button): add type="button" on button to close modal and not submit

- packages/~/moderations/ui/src/Actions/RefusalModal.tsx
- packages/~/moderations/ui/src/Actions/ResponseMessageSelector.tsx
don't hide de modal if the request is not successful
> fix(moderation): use keydow and change to detect input changes

- e2e/features/moderations/jean_bon_do_not_join_dinum.feature
- e2e/features/moderations/jean_bon_join_abracadabra.feature
- e2e/features/moderations/marie_bon_join_bosch.feature
- packages/~/app/ui/src/button/components/copy.tsx
- packages/~/moderations/api/src/:id/page.tsx
- packages/~/moderations/ui/src/Actions/AcceptModal.tsx
- packages/~/moderations/ui/src/Actions/Actions.tsx
- packages/~/moderations/ui/src/Actions/RefusalModal.tsx
- packages/~/moderations/ui/src/Actions/TagInput.tsx
- packages/~/moderations/ui/src/Actions/Toolbar.tsx
- packages/~/organizations/ui/src/info/About.tsx
- packages/~/organizations/ui/src/info/Investigation.tsx
- packages/~/organizations/ui/src/info/__snapshots__/About.test.tsx.snap
- packages/~/organizations/ui/src/info/__snapshots__/Investigation.test.tsx.snap
- packages/~/users/ui/src/About/About.tsx
<p align="center"><img src="https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExbHZxdzJvenZjZmwzM3F6cTA4YjgxMG9qY2w2M3owM3Jpemk1N2ZzNiZlcD12MV9naWZzX3NlYXJjaCZjdD1n/wqwgjoFoRR5quOPLsi/giphy.gif"></p>
> fix(ui): improvement following PR flow 3

- e2e/features/moderations/jean_bon_do_not_join_dinum.feature
- e2e/features/moderations/jean_bon_join_abracadabra.feature
- packages/~/moderations/ui/src/Actions/AcceptModal.tsx
- packages/~/moderations/ui/src/Actions/RefusalModal.tsx
<p align="center"><img src="https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExMWtlYjNyN2lpY3VuMHpxMjFmc2dvdDhjMDdpZjZpOThvaTdodDVlZyZlcD12MV9naWZzX3RyZW5kaW5nJmN0PWc/Jalikml2XiUgw/giphy.gif"></p>
> wording(moderations): update informations into acceptal & refusal modals

- README.md
<p align="center"><img src="https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExdzNmenc1eTk5cGcxZjFoNDc3YnJ3MXoxaXFhMmFsN3F0czZtYm83YSZlcD12MV9naWZzX3NlYXJjaCZjdD1n/7YYnbY5J1yvn0LUj8z/giphy.gif"></p>
> doc(readme): update readme with deployment process

- e2e/features/moderations/jean_bon_join_abracadabra.feature
- e2e/features/moderations/marie_bon_join_bosch.feature
- packages/~/moderations/ui/src/Actions/AcceptModal.tsx
<p align="center"><img src="https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExc2hiemI1cGYwanM0MHNrc2VoMDl6dnNhenpjdmphMXluMnBscms2bCZlcD12MV9naWZzX3NlYXJjaCZjdD1n/3yJNOJ2NQmu4w/giphy.gif"></p>
> fix(moderation): add sendNotification component

- bun.lock
- package.json
- packages/~/app/api/package.json
- packages/~/app/core/package.json
- packages/~/app/core/tsconfig.json
- packages/~/app/layout/package.json
- packages/~/app/layout/tsconfig.json
- packages/~/app/sentry/package.json
- packages/~/app/sentry/tsconfig.json
- packages/~/app/ui/tsconfig.json
- packages/~/app/urls/tsconfig.json
- packages/~/config/typescript/base/tsconfig.json
- packages/~/config/typescript/bun/tsconfig.json
- packages/~/config/typescript/package.json
- packages/~/infra/crisp/middleware/package.json
- packages/~/infra/moncomptepro/database/tsconfig.json
- packages/~/infra/zammad/api/package.json
- packages/~/infra/zammad/api/tsconfig.json
- packages/~/moderations/lib/package.json
- packages/~/moderations/ui/package.json
- packages/~/organizations/api/package.json
- packages/~/users/ui/package.json
- packages/~/welcome/api/package.json
- packages/~/welcome/api/tsconfig.json
- tsconfig.json
> chore(pkg): update to @types/bun

- CONTRIBUTING.md
internal source: https://documentation.beta.numerique.gouv.fr/doc/standards-de-contribution-pc-gQwQpAV4Ro
> 📝 add CONTRIBUTING.md

- e2e/cypress/support/step_definitions/mockserver.ts
- e2e/features/auth/connexion.feature
- e2e/features/moderations/jean_bon_do_not_join_dinum.feature
- e2e/features/moderations/jean_bon_join_abracadabra.feature
- e2e/features/moderations/marie_bon_join_bosch.feature
- e2e/features/moderations/pierre_bon_join_aldp.feature
- e2e/features/moderations/reprocess_marie_bon_bosch.feature
- e2e/features/moderations/richard_bon_join_dengi.feature
- e2e/features/organizations/dinum.feature
- e2e/features/organizations/yes_we_hack_domain_verification.feature
- e2e/features/users/jean_bon.feature
- e2e/features/users/raphael.feature
<p align="center"><img src="https://media2.giphy.com/media/v1.Y2lkPTc5MGI3NjExam90cnJ2YTk3eHowbjl2cjk2ZDU0bWpjMzFwd2VkZHZ3OWIwcGQxciZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/xT0Gqe9Ap0qSOLicKc/giphy.gif"></p>
> ✏️  improve cucumber sentences
